# -*- coding: utf-8 -*-
"""PRPO3_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16BSMDUHK_3EWiF4bcvFFT4zv2IZhBJXM
"""

import math
import numpy  as np
import random as random

# integers array
int_arr = np.random.randint(0, 100, 10)
print(int_arr)

# Iterate arrays and find %3 number
for i in int_arr:
     if i % 3 == 0: print(i)